# NOTE: there is no such thing as a working "by-default" configuration file. 
#       At least the prefix needs to be specified.  Please consult the radvd.conf(5)
#       man page and/or /usr/share/doc/radvd-*/radvd.conf.example for help.
#
#
interface eth0
{
    AdvSendAdvert on;
    MinRtrAdvInterval 1350;
    MaxRtrAdvInterval 1800;
    AdvDefaultLifetime 0;
    # AdvDefaultPreference low;

    # AS13335 https://www.cloudflare.com/ips-v6/
    route 2400:cb00::/32 {};
    route 2606:4700::/32 {};
    route 2803:f800::/32 {};
    route 2405:b500::/32 {};
    route 2405:8100::/32 {};
    route 2a06:98c0::/29 {};
    route 2c0f:f248::/32 {};

    # # Cloudflare Tiers https://cf.sjr.dev/tools/connection
    # ## AI Gateway
    # route 2606:4700:78::90:0:0/112 {}; # gateway.ai.cloudflare.com, opencode.ai
    # ## Private Relay
    # route 2606:4700:101::/96 {}; # privacy-relay.cloudflare.com, apple-relay.cloudflare.com, masque-relay.cloudflare.com
    # route 2606:4700:10f::/96 {};
    # route 2606:4700:3055::/96 {};
    # route 2606:4700:3056::/96 {};
    # ## Enterprise
    # route 2606:4700::/96 {}; # cloudflare.com, trycloudflare.com, dap.pat-issuer.cloudflare.com, challenges.cloudflare.com, abs.twimg.com.cdn.cloudflare.net
    # route 2606:4700:7::/96 {}; # onlinelibrary.wiley.com
    # route 2606:4700:4408::/96 {}; # chatgpt.com
    # route 2a06:98c1:3101::/96 {}; # chatgpt.com
    # route 2a06:98c1:3100::/96 {}; # www.cochranelibrary.com
    # ## Business
    # route 2606:4700:10::/96 {};
    # ## Pro
    # route 2606:4700:20::/96 {};
    # ## Free
    # route 2606:4700:3030::/45 {}; # workers.dev
    # ## pages.dev
    # route 2606:4700:310c::/96 {};

    # BYOIP
    ## Canva Pty Ltd
    route 2401:c2e0:8000::/44 {};
    ## Shopify, Inc.
    route 2620:127:f00c::/46 {};
    ## OpenAI
    # route 2a13:9500:1e4::/48 {};

    # AS209242 Cloudflare BYOIP Customers
    ## Box.com 
    # route 2620:117:bfb0::/44 {};
    ## Ecosia GmbH
    # route 2a14:71c0::/32 {};

    # ISP https://bgp.tools/as/13335#downstreams
    ## AS30103 Zoom Video Communications, Inc (Using aggregate routes via AS2914)
    route 2620:123:20fa::/47 {};
    ## AS399358 Anthropic, PBC
    route 2607:6bc0::/48 {};
};
