table inet qos {
  chain output {
    type filter hook output priority mangle;
    
    ip6 daddr fe00::/7 ip6 dscp set 45 # nd, mldv2, dhcpv6
  }
}

table ip6 nat {
	chain postrouting {
		type nat hook postrouting priority srcnat; policy accept;
		oifname "CloudflareWARP" masquerade
	}
}

table ip nat {
    chain postrouting {
        type nat hook postrouting priority srcnat;
        oifname "CloudflareWARP" masquerade
    }
}
