table ip nat {
    chain postrouting {
        type nat hook postrouting priority srcnat;
        # Discord ICE from *.discord.media.
        oifname "CloudflareWARP" ip daddr 104.29.128.0/19 snat to 100.96.0.2
        # mc.hypixel.net.
        oifname "CloudflareWARP" ip daddr 172.65.197.160/32 snat to 100.96.0.2
    }
}
